apiVersion: v1
kind: Service
metadata:
  name: okimochi-emotion-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: okimochi-emotion-api
  ports:
    - name: http
      port: 80
      targetPort: http
