apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: okimochi-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: okimochi-backend
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: okimochi-emotion-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: okimochi-emotion-api
  minReplicas: 2
  maxReplicas: 4
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
