apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: okimochi-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: okimochi-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: okimochi-emotion-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: okimochi-emotion-api
