apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - emotion-api-configmap.yaml
  - emotion-api-service.yaml
  - emotion-api-deployment.yaml
